name: SPSAeries

on:
  push:
    branches: [main, dev]

env:
  major: 0
  minor: 3
  patch: ${{ github.run_number }}
  buildVer: 0.3.${{ github.run_number }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Build Script
      env:
        buildVer: ${{ env.buildVer }}
      run: pwsh -File ./build.ps1

    - name: Run Pester tests
      shell: pwsh
      run: |
        Import-Module ./SPSAeries/SPSAeries.psd1
        Invoke-Pester -Script "./Tests/*.Tests.ps1" -OutputFile "test-results.xml" -OutputFormat NUnitXml

    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml

  deploy:
      needs: test
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Run build script
        env:
          buildVer: ${{ env.buildVer }}
        run: pwsh -File ./build.ps1
    
      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name AeriesAPI -Force
  
      - name: Publish Module to PSGallery
        shell: pwsh
        run: |
          $PSGalleryApiKey = '${{ secrets.SPSAERIES_NUGET_API_KEY }}'
          Install-Module -Name PowerShellGet -Force
          Publish-Module -Path ./SPSAeries -NuGetApiKey $PSGalleryApiKey